package com.android.crazy.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val crazyLightPrimary = Color(0xFF343DFF)
val crazyLightOnPrimary = Color(0xFFFFFFFF)
val crazyLightPrimaryContainer = Color(0xFFE0E0FF)
val crazyLightOnPrimaryContainer = Color(0xFF00006E)
val crazyLightSecondary = Color(0xFF5C5D72)
val crazyLightOnSecondary = Color(0xFFFFFFFF)
val crazyLightSecondaryContainer = Color(0xFFE1E0F9)
val crazyLightOnSecondaryContainer = Color(0xFF191A2C)
val crazyLightTertiary = Color(0xFF843FA9)
val crazyLightOnTertiary = Color(0xFFFFFFFF)
val crazyLightTertiaryContainer = Color(0xFFF6D9FF)
val crazyLightOnTertiaryContainer = Color(0xFF310049)
val crazyLightError = Color(0xFFBA1A1A)
val crazyLightErrorContainer = Color(0xFFFFDAD6)
val crazyLightOnError = Color(0xFFFFFFFF)
val crazyLightOnErrorContainer = Color(0xFF410002)
val crazyLightBackground = Color(0xFFFFFBFF)
val crazyLightOnBackground = Color(0xFF1B1B1F)
val crazyLightSurface = Color(0xFFFFFBFF)
val crazyLightOnSurface = Color(0xFF1B1B1F)
val crazyLightSurfaceVariant = Color(0xFFE4E1EC)
val crazyLightOnSurfaceVariant = Color(0xFF46464F)
val crazyLightOutline = Color(0xFF777680)
val crazyLightInverseOnSurface = Color(0xFFF3EFF4)
val crazyLightInverseSurface = Color(0xFF303034)
val crazyLightInversePrimary = Color(0xFFBEC2FF)
val crazyLightShadow = Color(0xFF000000)
val crazyLightSurfaceTint = Color(0xFF343DFF)
val crazyLightOutlineVariant = Color(0xFFC7C5D0)
val crazyLightScrim = Color(0xFF000000)

val crazyDarkPrimary = Color(0xFFBEC2FF)
val crazyDarkOnPrimary = Color(0xFF0001AC)
val crazyDarkPrimaryContainer = Color(0xFF0000EF)
val crazyDarkOnPrimaryContainer = Color(0xFFE0E0FF)
val crazyDarkSecondary = Color(0xFFC5C4DD)
val crazyDarkOnSecondary = Color(0xFF2E2F42)
val crazyDarkSecondaryContainer = Color(0xFF444559)
val crazyDarkOnSecondaryContainer = Color(0xFFE1E0F9)
val crazyDarkTertiary = Color(0xFFE7B3FF)
val crazyDarkOnTertiary = Color(0xFF500075)
val crazyDarkTertiaryContainer = Color(0xFF6A238F)
val crazyDarkOnTertiaryContainer = Color(0xFFF6D9FF)
val crazyDarkError = Color(0xFFFFB4AB)
val crazyDarkErrorContainer = Color(0xFF93000A)
val crazyDarkOnError = Color(0xFF690005)
val crazyDarkOnErrorContainer = Color(0xFFFFDAD6)
val crazyDarkBackground = Color(0xFF1B1B1F)
val crazyDarkOnBackground = Color(0xFFE5E1E6)
val crazyDarkSurface = Color(0xFF1B1B1F)
val crazyDarkOnSurface = Color(0xFFE5E1E6)
val crazyDarkSurfaceVariant = Color(0xFF46464F)
val crazyDarkOnSurfaceVariant = Color(0xFFC7C5D0)
val crazyDarkOutline = Color(0xFF91909A)
val crazyDarkInverseOnSurface = Color(0xFF1B1B1F)
val crazyDarkInverseSurface = Color(0xFFE5E1E6)
val crazyDarkInversePrimary = Color(0xFF343DFF)
val crazyDarkShadow = Color(0xFF000000)
val crazyDarkSurfaceTint = Color(0xFFBEC2FF)
val crazyDarkOutlineVariant = Color(0xFF46464F)
val crazyDarkScrim = Color(0xFF000000)


val seed = Color(0xFF0000FF)