package com.android.crazy.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val light_primary = Color(0xFF4E57A9)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFDFE0FF)
val light_onPrimaryContainer = Color(0xFF000965)
val light_secondary = Color(0xFF5C5D72)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFE1E0F9)
val light_onSecondaryContainer = Color(0xFF181A2C)
val light_tertiary = Color(0xFF5A54A8)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE3DFFF)
val light_onTertiaryContainer = Color(0xFF140463)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1B1B1F)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1B1B1F)
val light_surfaceVariant = Color(0xFFE3E1EC)
val light_onSurfaceVariant = Color(0xFF46464F)
val light_outline = Color(0xFF777680)
val light_inverseOnSurface = Color(0xFFF3F0F4)
val light_inverseSurface = Color(0xFF303034)
val light_inversePrimary = Color(0xFFBDC2FF)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF4E57A9)
val light_outlineVariant = Color(0xFFC7C5D0)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFBDC2FF)
val dark_onPrimary = Color(0xFF1D2678)
val dark_primaryContainer = Color(0xFF353E90)
val dark_onPrimaryContainer = Color(0xFFDFE0FF)
val dark_secondary = Color(0xFFC4C4DD)
val dark_onSecondary = Color(0xFF2D2F42)
val dark_secondaryContainer = Color(0xFF444559)
val dark_onSecondaryContainer = Color(0xFFE1E0F9)
val dark_tertiary = Color(0xFFC5C0FF)
val dark_onTertiary = Color(0xFF2B2277)
val dark_tertiaryContainer = Color(0xFF423B8E)
val dark_onTertiaryContainer = Color(0xFFE3DFFF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1B1B1F)
val dark_onBackground = Color(0xFFE4E1E6)
val dark_surface = Color(0xFF1B1B1F)
val dark_onSurface = Color(0xFFE4E1E6)
val dark_surfaceVariant = Color(0xFF46464F)
val dark_onSurfaceVariant = Color(0xFFC7C5D0)
val dark_outline = Color(0xFF91909A)
val dark_inverseOnSurface = Color(0xFF1B1B1F)
val dark_inverseSurface = Color(0xFFE4E1E6)
val dark_inversePrimary = Color(0xFF4E57A9)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFBDC2FF)
val dark_outlineVariant = Color(0xFF46464F)
val dark_scrim = Color(0xFF000000)


val seed = Color(0xFF545A92)